name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch private tests
      uses: actions/checkout@v4
      with:
        repository: Bad-4-Robots/add-two-tests
        token: ${{ secrets.TEST_REPO_PAT }}
        path: temp_tests

    - name: Move test file to roott
      run: |
        mv temp_tests/run_tests.py test_add_numbers.py
        rm -rf temp_tests

    - name: test
      id: test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: ''
        test-command: 'PYTHONPATH=. pytest test_add_numbers.py -v'
        max-score: 100

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test
        points: |
          test_positive_numbers=40
          test_negative_numbers=30
          test_decimal_numbers=30